name: build-2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  schedule:
    - cron: '0 8 */6 * *' # every 6 days to keep cache
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  DOCKERHUB_SLUG: ac1dburn/rtorrent-rutorrent-cross-seed
  GHCR_SLUG: ghcr.io/ac1dburnz/rtorrent-rutorrent-cross-seed

jobs:
  build:
    uses: ac1dburn/.github/.github/workflows/bake-distribute-mp.yml@0acc187b016a2946786f201397bbcfb2c530ffc7
    permissions:
      # same as global permissions
      contents: read
      # required to push to GHCR
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            image: ac1dburn/rtorrent-rutorrent-cross-seed
            login-registry: docker.io
            login-username: ac1dburn
            login-secret-key: DOCKER_PASSWORD
          -
            image: ghcr.io/ac1dburn/rtorrent-rutorrent-cross-seed
            login-registry: ghcr.io
            login-username: ${{ github.repository_owner }}
            login-secret-key: GITHUB_TOKEN
    with:
      target: image-all
      push: ${{ github.event_name != 'pull_request' }}
      cache: true
      cache-scope: build
      meta-image: ${{ matrix.image }}
      meta-tags: |
        type=match,pattern=(.*)-r,group=1
        type=ref,event=pr
        type=edge
      meta-labels: |
        org.opencontainers.image.title=rTorrent and ruTorrent
        org.opencontainers.image.description=rTorrent and ruTorrent
        org.opencontainers.image.vendor=ac1dburn
      login-registry: ${{ matrix.login-registry }}
      login-username: ${{ matrix.login-username }}
    secrets:
      login-password: ${{ secrets[matrix.login-secret-key] }}
